language: java
sudo: false
jdk: openjdk8
cache:
  directories:
    - $HOME/.m2
install: true
script: mvn clean package -DskipTests=true
notifications:
  email:
    on_success: "never"
    on_failure: "never"
deploy:
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: editor-backend-demo
    skip_cleanup: true
    on:
      all_branches: true