spring:
#  datasource:
#    hikari:
#      connectionTimeout: 20000
#      maximumPoolSize: 5
#    password: admin
#    url: jdbc:postgresql://localhost:5433/editor
#    username: postgres
  datasource:
    url: jdbc:postgresql://ec2-52-7-115-250.compute-1.amazonaws.com:5432/ddf65mbfgop3pu
    username: ${USERNAME}
    password: ${PASSWORD}
    platform: postgres


  jpa:
    hibernate:
      ddl-auto: update